import React, { useEffect, useMemo, useState } from "react";
import ForgeReconciler, { Box, Button, Checkbox, Heading, Label, SectionMessage, Select, Spinner, Stack, TextArea, Textfield, Toggle } from "@forge/react";
import { invoke } from "@forge/bridge";

const CORE_FIELDS = { tracking:"Tracking number field", deliveryStatus:"Delivery Status field (optional)", deliveryDate:"Delivered date field (optional)", signedFor:"Signed for field (optional)", dateSent:"Date sent / dispatched field (optional)", lastDhlCheck:"Last DHL check field (optional)", client:"Client / airline field (optional)" };
const ADVANCED_DHL_FIELDS = [
 {label:"Current DHL status",path:"status.description"},{label:"Current DHL status code",path:"status.statusCode"},{label:"Current status timestamp",path:"status.timestamp"},{label:"Estimated delivery",path:"estimatedTimeOfDelivery"},{label:"Estimated delivery from",path:"estimatedDeliveryTimeFrame.estimatedFrom"},{label:"Estimated delivery through",path:"estimatedDeliveryTimeFrame.estimatedThrough"},{label:"Latest event description",path:"events.0.description"},{label:"Latest event code",path:"events.0.statusCode"},{label:"Latest event timestamp",path:"events.0.timestamp"},{label:"Latest event location",path:"events.0.location.address.addressLocality"},{label:"Origin city",path:"origin.address.addressLocality"},{label:"Origin postcode",path:"origin.address.postalCode"},{label:"Origin country",path:"origin.address.countryCode"},{label:"Destination city",path:"destination.address.addressLocality"},{label:"Destination postcode",path:"destination.address.postalCode"},{label:"Destination country",path:"destination.address.countryCode"},{label:"DHL shipment / waybill ID",path:"id"},{label:"DHL service",path:"service"}
];
function option(value,label=value){return value?{label,value}:null;}
function CollapsibleSection({title,open,onToggle,children}){return <Box><Button appearance="subtle" onClick={onToggle}>{open?`▼ ${title}`:`▶ ${title}`}</Button>{open?<Box>{children}</Box>:null}</Box>}

function App(){
 const [config,setConfig]=useState(null),[hasApiKey,setHasApiKey]=useState(false),[apiKey,setApiKey]=useState(""),[metadata,setMetadata]=useState({fields:[],statuses:[]}),[deliveryOptions,setDeliveryOptions]=useState([]),[previewFields,setPreviewFields]=useState([]),[activityLog,setActivityLog]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[testing,setTesting]=useState(false),[message,setMessage]=useState(null),[testTracking,setTestTracking]=useState("");
 const [openSections,setOpenSections]=useState({general:true,api:true,core:true,status:false,advanced:false,log:false});
 const [openStatuses,setOpenStatuses]=useState({});
 const toggleSection=k=>setOpenSections(o=>({...o,[k]:!o[k]}));
 const toggleStatus=k=>setOpenStatuses(o=>({...o,[k]:!o[k]}));
 const reloadLog=async()=>{try{setActivityLog((await invoke("getActivityLog"))||[])}catch{setActivityLog([])}};
 useEffect(()=>{Promise.all([invoke("getSettings"),invoke("getJiraMetadata"),invoke("getActivityLog")]).then(([s,m,l])=>{setConfig(s.config);setHasApiKey(s.hasApiKey);setMetadata(m);setActivityLog(l||[])}).catch(e=>setMessage({appearance:"error",title:"Unable to load settings",body:String(e)})).finally(()=>setLoading(false))},[]);
 useEffect(()=>{const f=config?.fields?.deliveryStatus;if(!f){setDeliveryOptions([]);return}invoke("getFieldOptions",{fieldId:f}).then(i=>setDeliveryOptions(i||[])).catch(()=>setDeliveryOptions([]))},[config?.fields?.deliveryStatus]);
 const fieldOptions=useMemo(()=>metadata.fields.map(f=>({label:`${f.name} (${f.id})`,value:f.id})),[metadata.fields]);
 const fieldName=id=>metadata.fields.find(f=>f.id===id)?.name||id||"";
 const selectedFieldOption=id=>id?option(id,fieldName(id)):null;
 const statusOptions=useMemo(()=>[{label:"— Do not transition —",value:""},...metadata.statuses.map(s=>({label:s.name,value:s.name}))],[metadata.statuses]);
 const deliveryStatusOptions=useMemo(()=>[{label:"— Do not update Delivery Status —",value:""},...deliveryOptions.map(i=>({label:i.value,value:i.value}))],[deliveryOptions]);
 const advancedDhlOptions=useMemo(()=>ADVANCED_DHL_FIELDS.map(i=>({label:i.label,value:i.path})),[]);
 if(loading||!config)return <Spinner size="large"/>;
 const updateRoot=(k,v)=>setConfig(o=>({...o,[k]:v}));
 const updateField=(k,v)=>setConfig(o=>({...o,fields:{...o.fields,[k]:v}}));
 const updateStatusMapping=(i,p)=>setConfig(o=>{const r=[...(o.statusMappings||[])];r[i]={...r[i],...p};return{...o,statusMappings:r}});
 const updateAdditionalMapping=(i,p)=>setConfig(o=>{const r=[...(o.additionalFieldMappings||[])];r[i]={...r[i],...p};return{...o,additionalFieldMappings:r}});
 const addAdvancedMapping=()=>setConfig(o=>({...o,additionalFieldMappings:[...(o.additionalFieldMappings||[]),{label:"",dhlPath:"",jiraFieldId:""}]}));
 const removeAdvancedMapping=i=>setConfig(o=>({...o,additionalFieldMappings:(o.additionalFieldMappings||[]).filter((_,x)=>x!==i)}));
 const save=async()=>{setSaving(true);setMessage(null);try{const r=await invoke("saveSettings",{config,dhlApiKey:apiKey});setHasApiKey(r.hasApiKey);setApiKey("");setMessage({appearance:"confirmation",title:"Settings saved",body:"The scheduler will use these settings on its next run."});await reloadLog()}catch(e){setMessage({appearance:"error",title:"Could not save settings",body:String(e)})}finally{setSaving(false)}};
 const inspectTracking=async()=>{setTesting(true);setMessage(null);try{const r=await invoke("inspectDhlTracking",{trackingNumber:testTracking});setPreviewFields(r.fields||[]);setMessage({appearance:r.shipmentFound?"confirmation":"warning",title:r.shipmentFound?"DHL connection successful":"No shipment returned",body:r.description||"DHL API responded successfully."})}catch(e){setMessage({appearance:"error",title:"DHL test failed",body:String(e)})}finally{setTesting(false)}};
 const clearLog=async()=>{await invoke("clearActivityLog");setActivityLog([])};
 const latestRun=activityLog.find(e=>e.action==="Scheduler complete"||e.action==="Scheduler completed"||e.action==="Scheduler started");
 const lastError=activityLog.find(e=>e.level==="error");
 return <Stack space="space.500">
  <Heading as="h1">DHL Tracking for Jira — Settings</Heading>
  <SectionMessage appearance={config.enabled&&hasApiKey?"confirmation":"warning"} title="System status">Tracking: {config.enabled?"Enabled":"Disabled"} | DHL API key: {hasApiKey?"Configured":"Not configured"} | Last activity: {latestRun?.timestamp||"No scheduler activity recorded yet"}{lastError?` | Last error: ${lastError.details||lastError.action}`:""}</SectionMessage>
  {message&&<SectionMessage appearance={message.appearance} title={message.title}>{message.body}</SectionMessage>}
  <CollapsibleSection title="General" open={openSections.general} onToggle={()=>toggleSection("general")}><Stack space="space.200"><Toggle id="enabled" isChecked={Boolean(config.enabled)} onChange={()=>updateRoot("enabled",!config.enabled)}/><Label labelFor="projectKey">Jira project key</Label><Textfield id="projectKey" value={config.projectKey||""} onChange={e=>updateRoot("projectKey",e.target.value)}/><Label labelFor="minDaysSinceSent">Minimum days since Date Sent</Label><Textfield id="minDaysSinceSent" type="number" value={String(config.minDaysSinceSent??0)} onChange={e=>updateRoot("minDaysSinceSent",Number(e.target.value))}/><Label labelFor="maxPerRun">Maximum tickets per run</Label><Textfield id="maxPerRun" type="number" value={String(config.maxPerRun??3)} onChange={e=>updateRoot("maxPerRun",Number(e.target.value))}/></Stack></CollapsibleSection>
  <CollapsibleSection title="DHL API & connection test" open={openSections.api} onToggle={()=>toggleSection("api")}><Stack space="space.200"><SectionMessage appearance="information">The test checks the DHL connection and previews a shipment. It does not create status mappings.</SectionMessage><Label labelFor="dhlApiKey">DHL API key {hasApiKey?"(already saved)":"(required)"}</Label><Textfield id="dhlApiKey" type="password" value={apiKey} placeholder={hasApiKey?"Leave blank to keep existing key":"Enter DHL API key"} onChange={e=>setApiKey(e.target.value)}/><Label labelFor="testTracking">Tracking number for connection test</Label><Textfield id="testTracking" value={testTracking} onChange={e=>setTestTracking(e.target.value)}/><Button onClick={inspectTracking} isLoading={testing}>Test DHL connection</Button>{previewFields.length>0&&<Box><Heading as="h3">Shipment preview</Heading>{previewFields.map(i=><SectionMessage key={i.path} appearance="information">{i.path}: {i.value}</SectionMessage>)}</Box>}</Stack></CollapsibleSection>
  <CollapsibleSection title="Core Jira field mapping" open={openSections.core} onToggle={()=>toggleSection("core")}><Stack space="space.200"><SectionMessage appearance="information">Choose the Jira fields used by this site. Field names are shown; IDs appear in the dropdown only for reference.</SectionMessage>{Object.entries(CORE_FIELDS).map(([k,l])=><Box key={k}><Label labelFor={`field-${k}`}>{l}</Label><Select inputId={`field-${k}`} options={fieldOptions} value={selectedFieldOption(config.fields?.[k])} onChange={s=>updateField(k,s?.value||"")}/></Box>)}</Stack></CollapsibleSection>
  <CollapsibleSection title="Standard DHL status → Jira mapping" open={openSections.status} onToggle={()=>toggleSection("status")}><Stack space="space.200"><SectionMessage appearance="information">Open only the DHL categories you want to configure. Each category maps to a Jira workflow status, Delivery Status value and optional internal comment.</SectionMessage>{(config.statusMappings||[]).map((row,index)=>{const key=row.category||String(index),open=Boolean(openStatuses[key]);return <Box key={key}><Button appearance="subtle" onClick={()=>toggleStatus(key)}>{open?"▼":"▶"} {row.label||row.category}{row.jiraStatus?` → ${row.jiraStatus}`:""}</Button>{open&&<Stack space="space.150"><Checkbox label="Enabled" isChecked={row.enabled!==false} onChange={()=>updateStatusMapping(index,{enabled:row.enabled===false})}/><Checkbox label="Terminal event — stop checking this shipment after it occurs" isChecked={Boolean(row.terminal)} onChange={()=>updateStatusMapping(index,{terminal:!row.terminal})}/><Label labelFor={`jira-status-${index}`}>Jira workflow status</Label><Select inputId={`jira-status-${index}`} options={statusOptions} value={option(row.jiraStatus||"",row.jiraStatus||"— Do not transition —")} onChange={s=>updateStatusMapping(index,{jiraStatus:s?.value||""})}/><Label labelFor={`delivery-status-${index}`}>Delivery Status field value</Label><Select inputId={`delivery-status-${index}`} options={deliveryStatusOptions} value={option(row.deliveryStatus||"",row.deliveryStatus||"— Do not update Delivery Status —")} onChange={s=>updateStatusMapping(index,{deliveryStatus:s?.value||""})}/><Label labelFor={`comment-${index}`}>Internal comment template (optional)</Label><TextArea id={`comment-${index}`} value={row.commentTemplate||""} onChange={e=>updateStatusMapping(index,{commentTemplate:e.target.value})}/></Stack>}</Box>})}</Stack></CollapsibleSection>
  <CollapsibleSection title="Advanced DHL → Jira field mappings" open={openSections.advanced} onToggle={()=>toggleSection("advanced")}><Stack space="space.300"><SectionMessage appearance="information">Optional. Use this only if you want extra DHL values written into Jira.</SectionMessage>{(config.additionalFieldMappings||[]).map((row,index)=><Box key={`advanced-${index}`}><Label labelFor={`advanced-label-${index}`}>Label</Label><Textfield id={`advanced-label-${index}`} value={row.label||""} onChange={e=>updateAdditionalMapping(index,{label:e.target.value})}/><Label labelFor={`advanced-dhl-${index}`}>DHL information</Label><Select inputId={`advanced-dhl-${index}`} options={advancedDhlOptions} value={option(row.dhlPath,ADVANCED_DHL_FIELDS.find(i=>i.path===row.dhlPath)?.label||row.dhlPath)} onChange={s=>{const m=ADVANCED_DHL_FIELDS.find(i=>i.path===s?.value);updateAdditionalMapping(index,{dhlPath:s?.value||"",label:row.label||m?.label||""})}}/><Label labelFor={`advanced-jira-${index}`}>Jira field</Label><Select inputId={`advanced-jira-${index}`} options={fieldOptions} value={selectedFieldOption(row.jiraFieldId)} onChange={s=>updateAdditionalMapping(index,{jiraFieldId:s?.value||""})}/><Button appearance="danger" onClick={()=>removeAdvancedMapping(index)}>Remove mapping</Button></Box>)}<Button onClick={addAdvancedMapping}>Add advanced field mapping</Button></Stack></CollapsibleSection>
  <CollapsibleSection title="Activity log" open={openSections.log} onToggle={()=>toggleSection("log")}><Stack space="space.200"><SectionMessage appearance="information">Recent scheduler and configuration activity. Each row shows when it happened, the Jira issue where applicable, the action and result/details.</SectionMessage><Button onClick={reloadLog}>Refresh log</Button>{activityLog.length===0?<SectionMessage appearance="information">No activity has been recorded yet. The next scheduler run will begin populating this log.</SectionMessage>:activityLog.slice(0,100).map((e,i)=><Box key={`${e.timestamp||"log"}-${i}`}><Heading as="h4">{e.timestamp||"Unknown time"} | {e.issueKey||"System"} | {e.action||"Activity"}</Heading><SectionMessage appearance={e.level==="error"?"error":e.level==="warning"?"warning":"information"}>{e.details||"Completed"}</SectionMessage></Box>)}<Button appearance="danger" onClick={clearLog}>Clear log</Button></Stack></CollapsibleSection>
  <Button appearance="primary" onClick={save} isLoading={saving}>Save settings</Button>
 </Stack>;
}
ForgeReconciler.render(<React.StrictMode><App/></React.StrictMode>);
